spring:
  application:
    name: springboot_start
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/minadevelop2?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 2270398619
    ##??hikari???
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
#  redis:
#    database: 6
#    host: 127.0.0.1
#    port: 6379
#    password:
#    jedis:
#      pool:
#        #????
#        min-idle: 0
#        # ????
#        max-idle: 5
#        #????????(???????)
#        max-wait: -1
#        #?????
#        max-active: 8
#        #??????
#    timeout: 10000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8090
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # ???????????10MB
      max-request-size: 100MB    # ?????????100MB
#??????
logging:
  config: classpath:log/logback_dev.xml
# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #???????package?????????
  typeAliasesPackage: com.weilai.ccSpringboot.*.entity
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    # ??MP3.0???banner
    banner: false
    db-config:
      table-prefix: cc_
      logic-delete-field: isValid
      #????  0:"???ID??", 1:"???", 2:"????ID",3:"???snowflake", 4:"????ID UUID", 5:"????snowflake";
      id-type: assign_id
      #????
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_null
      #???????
      table-underline: true
      # ??????
      # ????????1?????????Mybatis Plus??????
      logic-delete-value: 1
      # ?????????0?????????Mybatis Plus??????
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#knife4j:
#  enable: true
#  openapi:
#    title: Knife4j????
#    description: "`????`,**????**# aaa"
#    email: xiaoymin@foxmail.com
#    concat: weilai
#    url: https://docs.xiaominfo.com
#    version: v4.0
#    license: Apache 2.0
#    license-url: https://stackoverflow.com/
#    terms-of-service-url: https://stackoverflow.com/
#    group:
#      test1:
#        group-name: ????
#        api-rule: package
#        api-rule-resources:
#          - com.miku.minadevelop.modules
############## Sa-Token ?? (??: https://sa-token.cc) ##############
sa-token:
  # token ??????? cookie ???
  token-name: token
  # token ????????? ??30??-1 ??????
  timeout: 2592000
  # token ??????????????? token ???????????????????-1 ??????????
  active-timeout: -1
  # ?????????????? ?? true ???????, ? false ??????????
  is-concurrent: false
  # ????????????????? token ?? true ????????? token, ? false ????????? token?
  is-share: true
  # token ?????????uuid?simple-uuid?random-32?random-64?random-128?tik?
  token-style: uuid
  # ????????
  is-log: true
  sso:
    auth-url: http://127.0.0.1:8080/user/doLogin
    slo-url:

